nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        origin_regex: false
    paths:
        '^/': ~