version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  web:
    build: .
    command: bash -c "composer install && \
      php bin/console doctrine:migrations:diff --no-interaction && \
      php bin/console doctrine:migrations:migrate --no-interaction && \
      php bin/console api:openapi:export --output=public/api/docs.jsonld && \
      php -S 0.0.0.0:8000 -t public"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://yourusername:yourpassword@db:5432/yourdatabase
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network: