name: Symfony CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create app_network
      run: docker network create app_network

    - name: Run linter
      run: php php-cs-fixer.phar fix src/ --dry-run --stop-on-violation

    - name: Run tests
      run: php bin/phpunit